### ISSUE TITLE
Use TR?

### ISSUE THREAD

**Issue by mrjbq7** [AlexIljin/ulid#1]
https://github.com/AlexIljin/ulid/blob/59971dbd4c774be849e688c2d63b86cd2a9d27df/ulid.factor#L74

You can:

```factor
TR: normalize-ulid "ILO" "110" ;
```

**Comment by alex-ilin** [comment]
Done in c2c8d723ed0b94ba4a0022383e52c80f5210dd81, thanks for the suggestion. I never knew we had such a facility.
