### ISSUE TITLE
replicate-as

### ISSUE THREAD

**Issue by mrjbq7** [AlexIljin/ulid#2]
https://github.com/AlexIljin/ulid/blob/59971dbd4c774be849e688c2d63b86cd2a9d27df/ulid.factor#L18

```factor

: encode-bits2 ( n chars -- string )
    [ base /mod encoding nth ] "" replicate-as nip reverse! ;
```

**Comment by alex-ilin** [comment]
Thanks for the suggestion! Committed in 8dd7ca9d1128febe535e0e4bd5ecbd92f92a8bc2.
